# Generated by Django 5.1.5 on 2025-01-20 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_measurementtype_store_products_measurement_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='measurement_type',
            field=models.CharField(blank=True, choices=[('weight', 'Weight'), ('size', 'Size'), ('volume', 'Volume'), ('length', 'Length')], default='size', max_length=10, verbose_name='Measurement'),
            preserve_default=False,
        ),
    ]
