# Generated by Django 5.1.5 on 2025-01-20 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_alter_category_name_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementtype',
            name='short_name',
            field=models.CharField(max_length=5, verbose_name='Short Name'),
        ),
    ]
