# Generated by Django 5.1.5 on 2025-01-22 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0012_alter_products_measurement_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Title')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales')], default='inventory', max_length=10, verbose_name='Report Type')),
                ('file', models.FileField(upload_to='Reports/', verbose_name='File')),
            ],
            options={
                'verbose_name': 'Report',
                'verbose_name_plural': 'Reports',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['date_added', 'date_updated'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
        migrations.AlterUniqueTogether(
            name='products',
            unique_together={('name', 'measurement_value')},
        ),
    ]
