# Generated by Django 5.1.5 on 2025-01-22 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0013_report_alter_category_options_alter_sales_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'ordering': ['-date_added', '-date_updated'], 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
