# Generated by Django 5.1.5 on 2025-01-22 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_alter_sales_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='report',
            unique_together={('name', 'generated_on')},
        ),
        migrations.AddField(
            model_name='report',
            name='json',
            field=models.TextField(default=[], verbose_name='Report Data'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report',
            name='type',
            field=models.CharField(choices=[('inventory', 'Inventory Report'), ('sales', 'Sales Report')], default='inventory', max_length=10, verbose_name='Report Type'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('addition', 'Addition'), ('subtraction', 'Subtraction')], max_length=20)),
                ('quantity', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posApp.products')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='report',
            name='file',
        ),
    ]
