# Generated by Django 5.1.5 on 2025-01-22 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0015_alter_report_unique_together_report_json_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['generated_on'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
