# Generated by Django 5.1.5 on 2025-01-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_alter_report_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-generated_on'], 'verbose_name': 'Report', 'verbose_name_plural': 'Reports'},
        ),
    ]
