# Generated by Django 5.1.5 on 2025-01-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0017_alter_report_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='time_range',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('annual', 'Annual')], default='daily', max_length=10, verbose_name='Time Range'),
        ),
    ]
