# Generated by Django 5.1.5 on 2025-01-25 05:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0022_alter_products_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='served_by',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.RESTRICT, related_name='served_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
