# Generated by Django 5.1.5 on 2025-01-25 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0024_report_generated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
