# Generated by Django 5.1.5 on 2025-01-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0025_alter_products_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
