# Generated by Django 5.1.5 on 2025-01-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0026_alter_sales_date_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='price',
        ),
        migrations.AddField(
            model_name='products',
            name='buy_price',
            field=models.FloatField(default=0, verbose_name='Buy Price'),
        ),
        migrations.AddField(
            model_name='products',
            name='sell_price',
            field=models.FloatField(default=0, verbose_name='Sell Price'),
        ),
    ]
